### ISSUE TITLE
can't find dijo config file

### ISSUE THREAD

**Issue by alexawiley** [NerdyPepper/dijo#113]
Hi! I'm trying to customize dijo and having trouble opening the `config.toml` file

`zsh: no such file or directory: HOME/Library/Application`

**Comment by Regan-Koopmans** [comment]
Hi @alexawiley , could you try the following directory?
`vim ~/Library/Application\ Support/rs.nerdypepper.dijo/config.toml`

**Comment by alexawiley** [comment]
It worked! Thanks a lot.
