### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by rafamerlin** [NerdyPepper/dijo#13]
Hey, when I run cargo install on windows I'm having issues with termion

```
   Compiling termion v1.5.5
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\xxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.5\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?
```

I haven't tried to install it on linux yet, is this something that may be exclusive to my computer or something?

At the end it says it has failed to compile dijo v0.1.3

**Comment by NerdyPepper** [comment]
`dijo` does not support windows at the moment, because `termion` does not support windows at the moment. However, using the `crossterm` backend for cursive could help `dijo` run on windows, so I have made a [branch](https://github.com/NerdyPepper/dijo/tree/feature/windows) specifically for this. You can try it out with:

```
$ git clone -b feature/windows https://github.com/NerdyPepper/dijo/
$ cargo install --force --path ./dijo
```

`crossterm` is not built for powershell, but it has been tested console host on Win 10 and Win 8.1. Let me know how it goes, this would help make `dijo` truly cross platform. 

The only reason I am not using `crossterm` because it flashes the screen while redrawing.

**Comment by icyphox** [comment]
+1

**Comment by ntqr** [comment]
It looks like ncurses isn't supported on Windows:

```
error: failed to run custom build command for `ncurses v5.99.0`
...
c1: fatal error C1083: Cannot open source file: 'D:\apps\dijo\target\release\build\ncurses-a01b84948c9e0b70\out\chtype_size.c': Permission denied
```
Maybe consider using [pancurses](https://github.com/ihalila/pancurses)?

**Comment by NerdyPepper** [comment]
@ntqr the `cursive` crate uses `ncurses` as a default feature, which I have disabled as of [02bba5](https://github.com/NerdyPepper/dijo/commit/02bba52346d948e90fbc1b351486f0f1307c243d). This should work fine with either `crossterm` or `pancurses`.

I am working towards setting up CI and a testing suite for all platforms, please put up with my trial and error until then :sweat_smile:.

**Comment by jjn2009** [comment]
similarly maybe add a note in the WIKI about the ncurses library requirement for building from source in 18.04 solved this with: `apt install libncursesw5-dev`

**Comment by rafamerlin** [comment]
It did work now, but it does look a bit weird.

I can just see the highlighted test and the others just show if I use the arrows on my keyboard.

![dijo](https://user-images.githubusercontent.com/11574755/88756205-58a1da80-d1a6-11ea-8e17-852c0781c4ff.gif)

**Comment by NerdyPepper** [comment]
@rafamerlin was the text rendering fine with `crossterm`?

**Comment by rafamerlin** [comment]
I haven't tried it with Crossterm. I will try it tonight and will get back to you.

**Comment by rafamerlin** [comment]
So, I'm still a beginner on rust and I wasn't used to TUIs before.

Gave a quick look and saw that currently the one being used is `pancurses-backend` so on windows it will use `pdcurses-sys` so I checked out this commit which was in theory still using crossterm:  
https://github.com/NerdyPepper/dijo/commit/d7c303dda4750a432478c94b3ed41bca1352d839

However, when I try to build this one it will give me this issue:
```
error[E0432]: unresolved import `cursive::crossterm`
  --> src\main.rs:20:5
   |
20 | use cursive::crossterm;
   |     ^^^^^^^^^^^^^^^^^^ no `crossterm` in the root
```

I tried to add crossterm as a dependency just as a test but still doesn't work. Googled it but couldn't find anything as well. Maybe I'm missing something on my box?

**Comment by NerdyPepper** [comment]
@rafamerlin sweet, that seems to be working as expected. I have released v0.2.3 that fully supports windows with the crossterm backend. The installation process is similar:

```
cargo build --release --no-default-features --features "crossterm-backend"
```

Alternatively, you can download pre-compiled binaries from the release page.

Cheers.

**Comment by rafamerlin** [comment]
Thank you for all the help :)

**Comment by gentoid** [comment]
Just FYI guys. `cargo install --no-default-features --features "crossterm-backend"` work perfectly fine on Win 10 1909. Thank you for shipping this on the Windows platform :-)
