### ISSUE TITLE
No Wiki For Habit_File

### ISSUE THREAD

**Issue by yugonline** [NerdyPepper/dijo#15]
I am not well versed with Rust but I found a lot of code in git regarding filewatchers, json etc but none of this information is available on Wiki. Was wondering if there were plans to add this.

**Comment by NerdyPepper** [comment]
I didn't think of adding this because it is mostly abstracted away from the user. Might be worth documenting some of the internals of `dijo` as well.

**Comment by genuinebyte** [comment]
Regarding the files that `dijo` creates, I think it would be useful to document where the are stored. I like to know where my files are stored, for whatever reason, and I think other people might be the same way.

**Comment by NerdyPepper** [comment]
I am working on an "Internals" page for the wiki at the moment.
