### ISSUE TITLE
Allow "untracking" entries

### ISSUE THREAD

**Issue by fabienengels** [NerdyPepper/dijo#18]
Hi,

I created a habit with no goal then increase the count to one (get habit get strikethrough) then reducing to zero, the habit is still strikethrough while the counter is to zero.

![2020-07-20-125641_347x227_scrot](https://user-images.githubusercontent.com/858738/87930490-7a091500-ca88-11ea-849d-bcd943f52c74.png)

**Comment by NerdyPepper** [comment]
This is intentional. The goal for such habits is considered to be 0, that is, if you track it for the day, you are done with it, if you don't track it (don't click enter even once for the day), it's counted out. 

As of now, there is no way to "untrack" a habit for the day.

**Comment by fabienengels** [comment]
What if I just want to track an habit but I increase it by mistake ?

**Comment by NerdyPepper** [comment]
Ah, I understand what you mean, would you prefer if hitting `Backspace` on a 0, "untracks" it rather than leaving it at 0?

**Comment by fabienengels** [comment]
Untrack it seems to be a good solution IMHO

**Comment by NerdyPepper** [comment]
Gotcha! It certainly is more intuitive that way.
