### ISSUE TITLE
Auto habits are not updated when dijo is running.

### ISSUE THREAD

**Issue by noname890** [NerdyPepper/dijo#20]
When `dijo` is running and i update an auto tracked habit, either manually or with git hooks, the habit will not update.

Example:

This works:

```bash
dijo -c "track-up commits" && dijo
```

But this will **not** work:

```bash
dijo

dijo -c "track-up commits" # in another terminal
```

**Comment by NerdyPepper** [comment]
This feature has been implemented using file watchers, and `dijo` does indeed update data automatically every time you change data using the `-c` flag. However, `dijo` redraws the screen only on user events, unlike programs like `htop` which refresh at 30 FPS.

So doing things like changing focus with `hjkl` or hitting `Ctrl-l` would redraw the screen and auto-habits will be updated.
