### ISSUE TITLE
Too easy to delete

### ISSUE THREAD

**Issue by StevenBlack** [NerdyPepper/dijo#21]
Hands up ✋ if you typed `add` (forgetting the `:`) and deleted two dijos by mistake.

Deleting a dijo should not be so easy.

**Comment by agucova** [comment]
Gosh, the world is so small. Use your hosts daily!

On the other hand, yes, maybe a confirmation prompt would be nice?

**Comment by charles-l** [comment]
Yeah, undo support would be nice (I saw something in the notes.txt about undo being on the roadmap)

**Comment by NerdyPepper** [comment]
The general consensus seems to be that the `d` key bind causes more destruction than being useful (I, too, have had mixed feelings about it, it has been on "subject to change" status on the wiki). 

I can think of two solutions for delete:

 - remove `d`, make `:delete` more ergonomic (tab to complete or shortest match first)
 - retain `d`, add undo command

**Comment by StevenBlack** [comment]
Hi Akshay @NerdyPepper I love this app.  I'm using it to study and learn more about Rust 🦀 

I would think, remove `d`, make `:delete` more ergonomic (tab to complete or shortest match first) is the easier of the two options.

Because undo would be a big, big feature. After all, what could you potentially "undo"?  Answer: everything.  You'll be implementing that for a long time, with so many edge cases.  For example, undo the last "Enter", or undo the last "Backspace".  Then, before you know it, somebody will ask to undo an undo.  Forget it.

**Comment by NerdyPepper** [comment]
I grossly underestimated the possibilities of undo haha. 

> remove d, make :delete more ergonomic 

is the way to go, clearly.

**Comment by fredrb** [comment]
I tried `d` before reading the command reference and my expectation was to delete current time entry. Somehow it felt analogous to vim's delete line. 

> remove d, make :delete more ergonomic (tab to complete or shortest match first)

I can agree to that.

**Comment by boyander** [comment]
Yep, too easy to delete. Deleted entire day tracking records in just 2 keystrokes by just missing `:`

**Comment by NerdyPepper** [comment]
With release of `dijo` v0.2.0, the `d` key bind has been removed and tab-to-complete has been added to the command line! For example:
```shell
:d<Tab>
:delete
:delete f<Tab>
:delete french

# also works with remaining commands 
```

The wiki will be updated soon.
