### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by mroberts1** [NerdyPepper/dijo#244]
I've been coming back to this app on and off for several years now and each time end up giving up on it every time because the documentation is so unclear. There aren't even any specific examples to use as models. When I launch the app, I can add and delete habits and that's about it. Hitting v or V to toggle between DAY and WEEK mode doesn't work. I can't even figure out how to set a once-a-week record of taking out the trash. There are so many habit trackers out there that unless a new one is even relatively easy to understand, it simply won't be used.

**Comment by oppiliappan** [comment]
dijo is extensively documented in the [wiki](https://github.com/nerdypepper/dijo/wiki).
