### ISSUE TITLE
Github releases and binaries

### ISSUE THREAD

**Issue by michaelbeaumont** [NerdyPepper/dijo#28]
Do you plan on creating github releases (with binaries if possible)?

**Comment by NerdyPepper** [comment]
Yes, as @razagill suggested in another thread, I am looking to automate this via GitHub actions to release on tag.

**Comment by sbeckeriv** [comment]
I have a github action for running on every commit [1]. I think if you change the on to create [2] it will work for tags. Looking around you can find other examples. I added caching for the dependencies. If cached most builds are fast. My file adds libdbus-1-dev i dont remember if that was for termion or tui crates. It might be something you need if not its an easy remove. Hope it helps.

[1] https://gist.github.com/sbeckeriv/849774ee19f23aaaf9d5197ddbe97474
[2] https://docs.github.com/en/actions/reference/events-that-trigger-workflows#create

**Comment by NerdyPepper** [comment]
@sbeckeriv this is beautiful! Thank you for this, I am not too familiar with GitHub's actions, but this pretty much does everything `dijo` needs.

**Comment by NerdyPepper** [comment]
As of v0.2.0, `dijo` now receives a binary release on par with the versioning on crates.io!

Kudos to @sbeckeriv for setting up the action!
