### ISSUE TITLE
:help for in-program help?

### ISSUE THREAD

**Issue by remexre** [NerdyPepper/dijo#29]
Would list commands + keybinds

**Comment by remexre** [comment]
whoops, looks like this got added two hours ago, heh

**Comment by NerdyPepper** [comment]
The `:help` command is still a work in progress, it doesn't explain key binds yet.

**Comment by NerdyPepper** [comment]
I have decided that I will not be adding help commands for `keybinds`, the help for other commands / aliases will only display basic syntax.
