### ISSUE TITLE
Add support for reminders?

### ISSUE THREAD

**Issue by mhluska** [NerdyPepper/dijo#30]
It would be interesting if this had a way to remind me to do a certain habit. Maybe via `:remind habit-name 12pm`

**Comment by NerdyPepper** [comment]
I am afraid reminders are beyond the scope of this project :confused:

**Comment by mhluska** [comment]
@NerdyPepper but currently I have to use another habit tracker's reminder to remind me to use this habit tracker

**Comment by NerdyPepper** [comment]
Ah. Reminders require a lot of consideration:

 - should not be transient, kinda like a cronjob
 - added complexity of daily reminders/weekly reminders
 - added dependency on `dbus` for messaging/notifying 
 - added complexity of a `dijo` daemon that polls reminders until time of completion
