### ISSUE TITLE
Add a mode to switch from little dots to a larger symbol

### ISSUE THREAD

**Issue by natethinks** [NerdyPepper/dijo#32]
My terminal theme makes it nearly impossible to discern the difference between colors in the dots. This would be fixed for the binary daily tasks by allowing a mode using symbols such as X and O instead of colored dots. This would also make the app more accessible for the visually impaired.

**Comment by NerdyPepper** [comment]
I have already [written out the boiler plate](https://github.com/NerdyPepper/dijo/blob/master/src/utils.rs#L7) for this. You will soon be able to configure the character used via a config file.

**Comment by natethinks** [comment]
Awesome, thanks so much!

**Comment by NerdyPepper** [comment]
You can modify the characters and the colors used via a config file, as of v0.2.3! `dijo` creates a default config on first run, which you can use as reference.

The wiki will be updated soon, but if you are on macOS, the config file will be located at `/Users/yourname/Library/Preferences/rs.nerdypepper.dijo/config.toml` and if you are on GNU/Linux, the config file will be located at `/home/alice/.config/dijo/config.toml`.

If you are facing any issues with the config file, feel free to open a new issue.
