### ISSUE TITLE
Any plans to release on nixpkgs?

### ISSUE THREAD

**Issue by rpearce** [NerdyPepper/dijo#34]
https://github.com/nixos/nixpkgs

I looked for `dijo`, `$ nix-env -qaP | grep dijo`, but couldn't find it! I'd love to install `dijo` just like I do `cargo`, `rustc`, and `rustfmt`, and I bet others would, too.

https://github.com/rpearce/dotfiles/blob/master/nix/home.nix#L92-L95

Thanks for making this!

**Comment by NerdyPepper** [comment]
@Infinisil's [PR to add `dijo v0.1.5`](https://github.com/NixOS/nixpkgs/pull/93597) to nixpkgs was merged yesterday!

I will add instructions to the readme and the wiki later today.

**Comment by rpearce** [comment]
Amazing! And @Infinisil is a pretty nice Nix person, if I may add

**Comment by Infinisil** [comment]
@NerdyPepper My PR is now in the latest unstable channel, so dijo can now be installed with
```
$ nix-env -f channel:nixpkgs-unstable -iA dijo
```

This notably works on all Linux distros and macOS as well

**Comment by NerdyPepper** [comment]
Gotcha, I will add that to the readme/wiki, thanks a bunch @Infinisil!

**Comment by rpearce** [comment]
Yeah as of today it's on `nixpkgs-unstable` -- sorry I didn't update when I saw it released! Thanks, @Infinisil (I told you they were real a stand-up person)
