### ISSUE TITLE
Changing mode closes/crashes

### ISSUE THREAD

**Issue by AviiNuo** [NerdyPepper/dijo#4]
Dijo closes without saving if I try to switch to WEEK mode with "v" on a habit with no goal, or with "Shift + v" if there is a habit with no goal.

Also is there theming or keymap rebinding planned?

**Comment by AviiNuo** [comment]
#5 

this guy seems to have discovered the underlying cause.

**Comment by NerdyPepper** [comment]
Should be fixed on master, this fix will be included in release v0.1.3.

**Comment by Infinisil** [comment]
@NerdyPepper Awesome, can you also tag a release on GitHub? I can package it for [nixpkgs](https://github.com/NixOS/nixpkgs) then :)

**Comment by NerdyPepper** [comment]
Oops, I forgot to push tags, v0.1.4 is out now, with loads of initial bug fixes. Thanks a bunch for maintaining this package @Infinisil!

**Comment by Infinisil** [comment]
Will have to wait for the next release that includes the changes in https://github.com/NerdyPepper/dijo/commit/2a3be003015bac9c6a13549029b9fb4595e88384#diff-d2ede298d9a75c849170d6ef285eda1e (the nixpkgs Rust builder requires an up-to-date lockfile)

**Comment by NerdyPepper** [comment]
@Infinisil I will be releasing v0.1.5 today, hopefully that includes everything you need for the package.
