### ISSUE TITLE
Date recorded in habit_record.json is one day after the current date.

### ISSUE THREAD

**Issue by cy-b** [NerdyPepper/dijo#40]
Hi, really cool project, thanks!
There is one problem with dijo on my mac: the date recorded in habit_record.json is one day later than the current date (and the date shown on dijo UI), not sure why this happened. 

The dijo UI shows July 22:
<img width="672" alt="Screen Shot 2020-07-22 at 21 09 12" src="https://user-images.githubusercontent.com/7958498/88251408-990dcf80-cc5f-11ea-9e09-71106c2d91ee.png">

The json content shows July 23:
<img width="220" alt="Screen Shot 2020-07-22 at 21 10 44" src="https://user-images.githubusercontent.com/7958498/88251492-cfe3e580-cc5f-11ea-8ad5-eba0a1f7d2bd.png">

**Comment by NerdyPepper** [comment]
Fix for this bug was released with v0.2.0!

Let me know if the issue persists, timezones are weird.
