### ISSUE TITLE
Duplicate habits

### ISSUE THREAD

**Issue by fabienengels** [NerdyPepper/dijo#41]
Hi,

Currently (version 0.2.0), you can add two habits (or more) with the same name. Both of them will be displayed and saved and even deleted if you call :delete.

Maybe the add command should refuse the creation of a habit if there is already one with the same name ?

**Comment by NerdyPepper** [comment]
Yep, #33 fixes this.

**Comment by fabienengels** [comment]
Oups my bad, at least I'll check how it was implemented, a good way to learn :)

**Comment by NerdyPepper** [comment]
I'd like to keep this issue open unti #33 is merged :)
