### ISSUE TITLE
Add GNU/Linux path to Internals > Files documentation

### ISSUE THREAD

**Issue by christianboyle** [NerdyPepper/dijo#44]
It would be helpful for people running WSL/Ubuntu to add the GNU/Linux path `$HOME/.local/share/dijo/` here: https://github.com/NerdyPepper/dijo/wiki/Internals#files to avoid any confusion with Arch Linux.

**Comment by NerdyPepper** [comment]
That path is not specific to Arch Linux, it is selected for any OS that follows `XDG` spec.
