### ISSUE TITLE
Strikethrough regression

### ISSUE THREAD

**Issue by christianboyle** [NerdyPepper/dijo#55]
Completing your currently focused habit used to mark the habit label with a strikethrough, but that has ceased to be the case since `v2.2.0`. 

Working in `v2.1.0`:

![2 1 0](https://user-images.githubusercontent.com/1605754/88604812-d8606580-d03d-11ea-8fa2-f459f3f14473.gif)

Broken in `v2.2.0`:

![2 2 0](https://user-images.githubusercontent.com/1605754/88604822-deeedd00-d03d-11ea-8fc2-d54aca3e9cc2.gif)

**Comment by NerdyPepper** [comment]
Also caused by the switch to `pancurses`, wow I did *not* test that release properly :p

I will be tracking this over at #50 if you don't mind.
