### ISSUE TITLE
TERM of "screen" (tmux) makes unselected goal headers invisible

### ISSUE THREAD

**Issue by dballard** [NerdyPepper/dijo#56]
normal console launch 
> $ echo $TERM
> xterm-256color
![dijo xterm](https://user-images.githubusercontent.com/543120/88607572-69324380-d034-11ea-9323-cb1bbe888728.png)

> $ tmux
> $ echo term
> screen
![dijo-screen](https://user-images.githubusercontent.com/543120/88607627-89fa9900-d034-11ea-8432-de2b16984192.png)

**Comment by dballard** [comment]
Aaaah now I noticed the dots too this is basically a dup of #50

**Comment by NerdyPepper** [comment]
Yep, caused by the switch to `pancurses`, I will be tracking updates on this issue over at #50 if you don't mind.
