### ISSUE TITLE
[BUG] Habit name doesn't gets struck with a line after the goal has been met

### ISSUE THREAD

**Issue by mananapr** [NerdyPepper/dijo#59]
**Dijo Version** - 0.2.2
(I Installed it from the AUR)

[Screenshot](https://files.catbox.moe/qz4396.png)

As you can see in the screenshot, `gym` is a 0/1 goal and even though I have set it as completed, the name hasn't been struck with a line.

I don't really know if this is a bug or if it is something related to my font or terminal. I am using `st` terminal with `Iosevka` as my font. I am using a version of `Iosevka` that has been patched with NerdFonts support.

Let me know if you need anything else. Thanks!

**Comment by NerdyPepper** [comment]
This is an issue with `pancurses`. Should be fixed with v0.2.3, releasing later today.

Related conversation for `pancurses` related bugs can go into #50. 

I happen to have the exact same terminal/font choices :)
