### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by capnhawkbill** [NerdyPepper/dijo#6]
I wanted to make an aur package but you don't have license. I suggest something like [gplv3](https://www.gnu.org/licenses/gpl-3.0.txt).

**Comment by ghifarit53** [comment]
I checked the content of `Cargo.toml` and the license seems to be MIT

**Comment by capnhawkbill** [comment]
Ah i missed that I expected a LICENCE file.

**Comment by NerdyPepper** [comment]
Ill add a license file as well, the license field in `Cargo.toml` is not as explicit as having a text version in source root.

**Comment by NerdyPepper** [comment]
As of v0.1.3, the text for the license is included with the source.
