### ISSUE TITLE
Version 0.2.3 still has a Cargo.toml whose version is 0.2.2

### ISSUE THREAD

**Issue by herbygillot** [NerdyPepper/dijo#60]
https://github.com/NerdyPepper/dijo/blob/3dd8502895d17b4e1a8afb729feeef5ba6d0474e/Cargo.toml#L3

**Comment by NerdyPepper** [comment]
Oops, tagged the wrong commit, thanks for pointing this out!

GH Actions should update the release.

**Comment by herbygillot** [comment]
Works perfectly - thank you @NerdyPepper
