### ISSUE TITLE
ncurses-rs dependency causing build errors on ARM

### ISSUE THREAD

**Issue by cinerea0** [NerdyPepper/dijo#63]
While [attempting to package dijo for Void Linux](https://github.com/void-linux/void-packages/pull/23972), I became aware that dijo does not compile on ARM architectures. Based on build logs, this appears to be due to a dependency on `ncurses-rs`. This library has known problems compiling on ARM architectures (https://github.com/jeaye/ncurses-rs/issues/184, https://github.com/jeaye/ncurses-rs/issues/193), and it appears to be unmaintained as of November last year (The author is still around but is no longer addressing issues or merging pull requests). Luckily, there is [an open PR](https://github.com/jeaye/ncurses-rs/pull/194) that appears to solve this issue, but again it is unlikely that it will be merged. In order to fix this, you may have to fork `ncurses-rs`, merge the PR yourself, and use your fork as a dependency instead.

**Comment by NerdyPepper** [comment]
Shouldn't be a problem with the latest version of `dijo`: v0.2.3, the `pancurses` dependency (which depends on `ncurses-rs`) has been switched out for `termion`, so `dijo` no longer (transitively or directly) depends on `ncurses-rs`.


```diff

@@ -1,4 +1,4 @@
-dijo v0.2.2 (/home/np/code/rustuff/dijo)
+dijo v0.2.3 (/home/np/code/rustuff/dijo)
 ├── chrono v0.4.13
 │   ├── num-integer v0.1.43
 │   │   └── num-traits v0.2.12
@@ -108,18 +108,10 @@
 │   ├── lazy_static v1.4.0
 │   ├── libc v0.2.73
 │   ├── log v0.4.11 (*)
-│   ├── maplit v1.0.2
-│   ├── pancurses v0.16.1
-│   │   ├── libc v0.2.73
-│   │   ├── log v0.4.11 (*)
-│   │   └── ncurses v5.99.0
-│   │       └── libc v0.2.73
-│   │       [build-dependencies]
-│   │       ├── cc v1.0.58
-│   │       └── pkg-config v0.3.18
 │   ├── signal-hook v0.1.16 (*)
-│   ├── term_size v0.3.2
-│   │   └── libc v0.2.73
+│   ├── termion v1.5.5
+│   │   ├── libc v0.2.73
+│   │   └── numtoa v0.1.0
 │   ├── unicode-segmentation v1.6.0
 │   └── unicode-width v0.1.8
 ├── directories v3.0.1
@@ -161,6 +153,8 @@
 │   ├── itoa v0.4.6
 │   ├── ryu v1.0.5
 │   └── serde v1.0.114 (*)
+├── toml v0.5.6
+│   └── serde v1.0.114 (*)
 └── typetag v0.1.5
     ├── erased-serde v0.3.12 (*)
     ├── inventory v0.1.7
```

Feel free to reopen if you face any issues, and thanks for all the help with packaging for voidlinux!
