### ISSUE TITLE
Feature: move between days

### ISSUE THREAD

**Issue by td0m** [NerdyPepper/dijo#64]
I often find myself forgetting to check habits on the day I complete them, and I'm sure others will find that useful.
Is there any way to *"time travel"* to previous days to change values?

**Comment by alichtman** [comment]
Without this feature, I really struggle to use this program. It has so much potential to be useful, though.

**Comment by NerdyPepper** [comment]
I'm on it!

**Comment by alichtman** [comment]
I think `h,j,k,l` should be used for day-to-day motion, and `shift+h,j,k,l` for habit-to-habit motion.

**Comment by skbolton** [comment]
I think it makes sense to focus in on a habit and zoom it into view. Then have hjkl move around the days of the habit to mark them.

**Comment by NerdyPepper** [comment]
This is currently being worked on at the `cursor` branch. You can install it manually and test it out, there are no breaking changes.

@skbolton that was my initial thought as well, but creating a new view involves a lot of work (view drawing rules, event handling, passing data in and out). Currently, the focused habit reveals a "cursor", you can move this cursor with WASD (subject to change), and make modifications. Moving beyond the current month triggers a "time travel" (similar to pressing `[` on the keyboard).

**Comment by alichtman** [comment]
Looks great. Any idea when it'll be in `master`?

**Comment by NerdyPepper** [comment]
Done!

With v0.2.6, you can change entries for past days, use ```Shift-{h,j,k,l}``` to move between days, reset the cursor with `}`. The next release will (hopefully) contain a keybind configuration option as well.

**Comment by a-y-u-s-h** [comment]
`Shift-{h,j,k,l}` or `Shift-{left,up,right,down}` to move between days isn't working for me for some reason.
