### ISSUE TITLE
14% Seems to be the maximum % per week 

### ISSUE THREAD

**Issue by Zeioth** [NerdyPepper/dijo#7]
On week mode, the goal counts as completed when it reach 14%, instead of 100%.
![perc](https://user-images.githubusercontent.com/3357792/87886018-1ba54d80-ca1a-11ea-9187-bdce23c63fe7.png)

**Comment by NerdyPepper** [comment]
I've been meaning to document how the different modes work, in week mode, 100% is reached only when you finish your goals for *every day* of the week. That means, reaching the goal for a given day counts for 100/7 = 14.28% towards that week, and that is the maximum possible contribution you can do towards your weekly goal in *one day*.

I am open to different ideas on tracking this, for example, would you prefer overshooting your goal for a day count towards the weekly goal?

**Comment by Zeioth** [comment]
I'd say it's enough with documentation. Design wise it's pretty solid.

**Comment by NerdyPepper** [comment]
This behavior is now documented under the [Modes](https://github.com/NerdyPepper/dijo/wiki/Modes) page.
