### ISSUE TITLE
How do you use the `false` values?

### ISSUE THREAD

**Issue by Siilwyn** [NerdyPepper/dijo#82]
:wave: hi, been using `dijo` happily for some months now. Was wondering how do you use the stored `false` values? I only have some that I created by mistake when I accidentally checked off a day but 'undo-ed' it.

**Comment by NerdyPepper** [comment]
With boolean habits, the `false` value is the same as not tracking it for that day (it doesn't affect weekly completion percentages). It exists as a visual cue, to allow the user to differentiate between the days on which they explicitly tracked the habit from the days that they forgot to track the habit. I personally felt that a three-valued (true, false, untracked) data type offered more information over a two-valued data type (true, untracked).

Hope that helps!
