### ISSUE TITLE
The build for this broke, due to external crate change.

### ISSUE THREAD

**Issue by assarbad** [NerdyPepper/dijo#86]
Please check [this ticket](https://github.com/nushell/nushell/issues/2866) for some details. From what it looks like, `dijo` is also affected by this.

The claim is that [this commit](https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7) broke it.

It surfaces as follows (vanilla `cargo install dijo`):

```
error[E0432]: unresolved import `syn::export`
  --> /home/oliver/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.5.0/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `enumset_derive`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `dijo v0.2.3`, intermediate artifacts can be found at `/tmp/cargo-installktPB8y`

Caused by:
  build failed
```

[This pull request](https://github.com/nushell/nushell/pull/2868) is said to work around the issue by pinning the `syn` crate to version:

```
syn = "=1.0.57"
```

Best regards and thanks for your program.

**Comment by NerdyPepper** [comment]
Thanks for the heads up! `dijo` does not directly depend on `syn` however, I'll have to dig into this.

**Comment by NerdyPepper** [comment]
This issue should be fixed on master, I'll draft a release to fix this on crates.io as well.
