### ISSUE TITLE
Man pages?

### ISSUE THREAD

**Issue by salahdin-ahmed** [NerdyPepper/dijo#92]
Hi,
Is there any man pages for this project? The wiki is perfect but I think if it is turned into a man page it will decrease the distance between the user and the piece of info he wants, just type `man dijo` and that's it, compared to opening a browser, searching for the GitHub page of this project and finally opening the wiki. If the problem is a lack of people who can work on man pages, I can work on it, I will just transfer the wiki from markdown into Groff man pages format.
Thanks for reading my issue.

**Comment by NerdyPepper** [comment]
>Is there any man pages for this project?

Nope, I haven't got around to learning how to or making one. 

>I can work on it, I will just transfer the wiki from markdown into Groff man pages format.

I would very much like that, thanks for the help!

**Comment by NerdyPepper** [comment]
Closed by #94.
