### ISSUE TITLE
v0.2.4 build problem

### ISSUE THREAD

**Issue by christianboyle** [NerdyPepper/dijo#95]
After running the following from a v0.2.3 install I get a build error:

```
$ rustup update
$ cargo install dijo
```

![2021-01-26_10-35-40AM](https://user-images.githubusercontent.com/1605754/105875888-fb0b1100-5fc3-11eb-8b79-5d08a4e3d9cb.png)

But if I clone the repo and run `cargo build` I can compile without issue:

![2021-01-26_10-41-19AM](https://user-images.githubusercontent.com/1605754/105875957-0eb67780-5fc4-11eb-8632-3c7669fd31dd.png)

Maybe something related to the different version of `cursive_core`?

**Comment by NerdyPepper** [comment]
Thanks for the quick feedback, #90 ought to fix this, not sure why `cargo install` and `cargo build` pull up different dependency graphs.

**Comment by NerdyPepper** [comment]
This is fixed by the latest (v0.2.5) release.
