### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by jonmed** [NerdyPepper/dijo#98]
Platform: Windows 10
Cargo version: 1.49.0

command used: `cargo install dijo`

error: could not compile `termion`

![image](https://user-images.githubusercontent.com/43858551/107458885-c0f94d80-6b33-11eb-97a0-2abdad6220db.png)

![image](https://user-images.githubusercontent.com/43858551/107458943-db332b80-6b33-11eb-8a31-c6c3c4831138.png)

**Comment by NerdyPepper** [comment]
I am afraid you can't install dijo from crates.io on windows currently (platform specific feature flags are nightly only).

I would suggest cloning the repo and running `cargo install --no-default-features --features "crossterm-backend"`, or downloading a pre-built binary from the releases page.

**Comment by NerdyPepper** [comment]
Related: #13

**Comment by jonmed** [comment]
OK. I didn't realize there were pre-built binaries. 
It seems to work fine.
Thank you.

**Comment by jonmed** [comment]
Maybe there could be a warning to Windows users in the readme about this issue, recommending the pre-built binary.
